version: '3.9'
services:
  backend:
    image: "duonganh203/be-cicd:latest"
    container_name: backend
    networks:
      - "test-cicd"
    ports:
      - "3000:3000"

  frontend:
    image: "duonganh203/fe-cicd:latest"
    container_name: frontend
    env_file:
      - .env
    depends_on:
      - "backend"
    networks:
      - "test-cicd"
    ports:
      - "4000:80"
 
networks:
  test-cicd:
    external: true
    name: test-cicd
