version: '3.8'
services:
  backend:
    image: ${{secrets.DOCKER_HUB_USERNAME}}/be-cicd:latest
    container_name: backend
    networks:
      - "test-cicd"
    ports:
      - "3000:4000"
  frontend:
    image: ${{secrets.DOCKER_HUB_USERNAME}}/fe-cicd:latest
    container_name: frontend
    depends_on:
      - "backend"
    networks:
      - "test-cicd"
    ports:
      - "4000:80"
networks:
  test-cicd:
    external: true
    name: test-cicd
