name: deploy
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build image
        run: |
          docker build ./fe/ -t ${{secrets.DOCKER_HUB_USERNAME}}/fe-cicd:latest
          docker build ./be/ -t ${{secrets.DOCKER_HUB_USERNAME}}/be-cicd:latest
      - name: Push image to docker dockerhub
        run: |
          docker login -u ${{secrets.DOCKER_HUB_USERNAME}} -p ${{secrets.DOCKER_HUB_TOKEN}}
          docker push ${{secrets.DOCKER_HUB_USERNAME}}/fe-cicd:latest
          docker push ${{secrets.DOCKER_HUB_USERNAME}}/be-cicd:latest
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: publish

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{secrets.SSH_PRIVATE_KEY1 }}

      - name: Copy docker-compose.yml
        run: scp -o StrictHostKeyChecking=no -r docker-compose.yml ${{secrets.SSH_USERNAME}}@${{secrets.SSH_HOST}}:/home/${{secrets.SSH_USERNAME}}/test-cicd/docker-compose.yml

      - name: Deploy with docker-compose
        run: |
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd /home/${{ secrets.SSH_USER }}/test-cicd
          docker pull ${{ secrets.DOCKER_USERNAME }}/fe-cicd:latest
          docker pull ${{ secrets.DOCKER_USERNAME }}/be-cicd:latest
          docker-compose down
          docker-compose up -d
          EOF
