name: deploy
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build image
        run: |
          docker build ./fe/ -t ${{secrets.DOCKER_HUB_USERNAME}}/fe-cicd:latest
          docker build ./be/ -t ${{secrets.DOCKER_HUB_USERNAME}}/be-cicd:latest
      - name: Push image to docker dockerhub
        run: |
          docker login -u ${{secrets.DOCKER_HUB_USERNAME}} -p ${{secrets.DOCKER_HUB_TOKEN}}
          docker push ${{secrets.DOCKER_HUB_USERNAME}}/fe-cicd:latest
          docker push ${{secrets.DOCKER_HUB_USERNAME}}/be-cicd:latest 


